//
//  ZMTSubModulesInteractor.swift
//  ZeusAppExternos
//
//  Created Pedro Ivan Soriano Flores on 13/01/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class ZMTSubModulesInteractor: ZMTSubModulesInteractorInputProtocol {
    weak var presenter: ZMTSubModulesInteractorOutputProtocol?
}
