//
//  VerificationCodeView.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 11/21/24.
//  Template generated by UPAX Zeus
//

import UIKit
import ZeusCoreDesignSystem
import ZeusSessionInfo

class VerificationCodeView: UIView {
    // MARK: Child views
    
    lazy var mainContainerView: UIView = {
        let view = UIView()
        view.translatesAutoresizingMaskIntoConstraints = false
        view.backgroundColor = .white
        return view
    }()
    
    lazy var zeusImage: UIImageView = {
        let image = UIImageView()
        image.translatesAutoresizingMaskIntoConstraints = false
        image.image = UIImage(named: "LogotypeZeus", in: .local, compatibleWith: nil)
        image.contentMode = .scaleAspectFit
        return image
    }()
    
    lazy var titleLabel: UILabel = {
        let lbl = UILabel()
        lbl.translatesAutoresizingMaskIntoConstraints = false
        lbl.font = UIFont(style: .bodyTextL(variant: .regular, isItalic: false))
        lbl.textColor = .black900
        lbl.textAlignment = .left
        lbl.numberOfLines = 0
        return lbl
    }()
    
    var validationCode: ZDSValidationCode = {
       var validation = ZDSValidationCode()
        validation.length = 6
        validation.keyboardType = .numberPad
        validation.font = .headline1(isItalic: false)
        validation.textContentType(.oneTimeCode)
        return validation
    }()
    
    lazy var errorLabel: UILabel = {
        let lbl = UILabel()
        lbl.translatesAutoresizingMaskIntoConstraints = false
        lbl.font = UIFont(style: .bodyTextS(variant: .regular, isItalic: false))
        lbl.textColor = .error
        lbl.textAlignment = .left
        lbl.text = "El código es incorrecto, intenta nuevamente."
        lbl.numberOfLines = 1
        lbl.isHidden = true
        return lbl
    }()
    
    lazy var forwardLabel: UILabel = {
        let lbl = UILabel()
        lbl.translatesAutoresizingMaskIntoConstraints = false
        lbl.font = UIFont(style: .bodyTextM(variant: .semiBold, isItalic: false))
        lbl.textColor = .mid500
        lbl.textAlignment = .center
        lbl.numberOfLines = 1
        return lbl
    }()
    
    lazy var underlineView: UIView = {
        let view = UIView()
        view.translatesAutoresizingMaskIntoConstraints = false
        view.backgroundColor = SessionInfo.shared.company?.primaryUIColor ?? .purple
        view.isHidden = true
        return view
    }()
    
    lazy var verifyBtn: ZDSButton = {
        var btn = ZDSButton()
        btn.style = .primary
        btn.setTitle("Verificar número", for: .normal)
        btn.primaryColor = SessionInfo.shared.company?.primaryUIColor ?? .purple
        btn.disabled = true
        return btn
    }()
    
    lazy var buttonView = verifyBtn.asUIKitView()
    
    // MARK: Initializers
    init(controller: VerificationCodeViewController) {
        super.init(frame: .zero)
        addViews()
        setupConstraints(parentController: controller)
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
