//
//  VerificationCodeView+Layout.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 11/21/24.
//  Template generated by UPAX Zeus
//

import UIKit
import ZeusCoreDesignSystem

extension VerificationCodeView {
    func addViews() {
        addSubview(mainContainerView)
        mainContainerView.addSubview(zeusImage)
        mainContainerView.addSubview(titleLabel)
        mainContainerView.addSubview(forwardLabel)
        mainContainerView.addSubview(underlineView)
        mainContainerView.addSubview(errorLabel)
        mainContainerView.addSubview(buttonView)
    }
    
    func setupConstraints(parentController: UIViewController) {
        let codeView = validationCode.asUIKitView(moveTo: parentController)
        mainContainerView.addSubview(codeView)
        NSLayoutConstraint.activate([
            mainContainerView.topAnchor.constraint(equalTo: topAnchor),
            mainContainerView.leadingAnchor.constraint(equalTo: leadingAnchor),
            mainContainerView.trailingAnchor.constraint(equalTo: trailingAnchor),
            mainContainerView.bottomAnchor.constraint(equalTo: bottomAnchor),
            
            zeusImage.centerXAnchor.constraint(equalTo: mainContainerView.centerXAnchor),
            zeusImage.topAnchor.constraint(equalTo: safeAreaLayoutGuide.topAnchor, constant: .mediumB),
            zeusImage.heightAnchor.constraint(equalToConstant: 27),
            zeusImage.widthAnchor.constraint(equalToConstant: 110),
            
            titleLabel.topAnchor.constraint(equalTo: zeusImage.bottomAnchor, constant: .largeA),
            titleLabel.leadingAnchor.constraint(equalTo: mainContainerView.leadingAnchor , constant: .smallB),
            titleLabel.trailingAnchor.constraint(equalTo: mainContainerView.trailingAnchor, constant: -.smallB),
            
            codeView.topAnchor.constraint(equalTo: titleLabel.bottomAnchor, constant: .largeA),
            codeView.leadingAnchor.constraint(equalTo: mainContainerView.leadingAnchor, constant: .smallB),
            codeView.trailingAnchor.constraint(equalTo: mainContainerView.trailingAnchor, constant: -.smallB),
            
            errorLabel.topAnchor.constraint(equalTo: codeView.bottomAnchor, constant: 8),
            errorLabel.leadingAnchor.constraint(equalTo: codeView.leadingAnchor),
            
            forwardLabel.centerXAnchor.constraint(equalTo: mainContainerView.centerXAnchor),
            forwardLabel.topAnchor.constraint(equalTo: codeView.bottomAnchor, constant: 80),
            
            underlineView.centerXAnchor.constraint(equalTo: forwardLabel.centerXAnchor),
            underlineView.topAnchor.constraint(equalTo: forwardLabel.bottomAnchor),
            underlineView.leadingAnchor.constraint(equalTo: forwardLabel.leadingAnchor),
            underlineView.trailingAnchor.constraint(equalTo: forwardLabel.trailingAnchor),
            underlineView.heightAnchor.constraint(equalToConstant: 0.5),
            
            buttonView.bottomAnchor.constraint(equalTo: mainContainerView.bottomAnchor, constant: -.smallB),
            buttonView.leadingAnchor.constraint(equalTo: mainContainerView.leadingAnchor , constant: .smallB),
            buttonView.trailingAnchor.constraint(equalTo: mainContainerView.trailingAnchor, constant: -.smallB),
        ])
    }
}
