//
//  ZeusBlogProtocols.swift
//  ZeusAppExternos
//
//  Created Alejandro Rivera on 26/09/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import Foundation
import ZeusUtils
import ZeusCoreDesignSystem
//MARK: Presenter -> Router
protocol ZeusBlogWireframeProtocol: AnyObject {
    
}

//MARK: View -> Presenter
protocol ZeusBlogPresenterProtocol: AnyObject {
    var interactor: ZeusBlogInteractorInputProtocol? { get set }
    
    func getURL()
}

//MARK: Interactor -> Presenter
protocol ZeusBlogInteractorOutputProtocol: AnyObject {
    func setURL(_ url: URL?)
    func setError(errorType: ZDSResultType)
}

//MARK: Presenter -> Interactor
protocol ZeusBlogInteractorInputProtocol: AnyObject {
    var presenter: ZeusBlogInteractorOutputProtocol?  { get set }
    
    func getURL()
}

//MARK: Presenter -> View
protocol ZeusBlogViewProtocol: AnyObject {
    var presenter: ZeusBlogPresenterProtocol?  { get set }
    
    func setURL(_ url: URL?)
    func setErrorScreen(errorType: ZDSResultType)
}
