//
//  ZeusBlogInteractor.swift
//  ZeusAppExternos
//
//  Created Alejandro Rivera on 26/09/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit
import ZeusUtils

class ZeusBlogInteractor: ZeusBlogInteractorInputProtocol {
    weak var presenter: ZeusBlogInteractorOutputProtocol?
    
    func getURL() {
        let url = URL(string: "https://talentozeus.com/blog")
        if !ZWSConnectionChecker.networkIsAvailable() {
            presenter?.setError(errorType: .errorInternet)
            return
        }
        presenter?.setURL(url)
    }
}
