//
//  ZeusBlogRouter.swift
//  ZeusAppExternos
//
//  Created Alejandro Rivera on 26/09/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class ZeusBlogRouter: ZeusBlogWireframeProtocol {
    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        let view = ZeusBlogViewController()
        let interactor = ZeusBlogInteractor()
        let router = ZeusBlogRouter()
        let presenter = ZeusBlogPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
