//
//  MyInformationViewView+Layout.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 11/21/24.
//  Template generated by UPAX Zeus
//

import UIKit

extension MyInformationViewView {
    func addViews() {
        addSubview(mainContainerView)
        mainContainerView.addSubview(mainScrollView)
        mainContainerView.addSubview(saveChangesView)
        mainScrollView.addSubview(inputsStackView)
        
    }
    
    func setupConstraints() {
        NSLayoutConstraint.activate([
            
                mainContainerView.topAnchor.constraint(equalTo: safeAreaLayoutGuide.topAnchor),
                mainContainerView.leadingAnchor.constraint(equalTo: leadingAnchor),
                mainContainerView.trailingAnchor.constraint(equalTo: trailingAnchor),
                mainContainerView.bottomAnchor.constraint(equalTo: bottomAnchor),
                
                mainScrollView.topAnchor.constraint(equalTo: mainContainerView.topAnchor, constant: 20),
                mainScrollView.leadingAnchor.constraint(equalTo: mainContainerView.leadingAnchor, constant: 16),
                mainScrollView.trailingAnchor.constraint(equalTo: mainContainerView.trailingAnchor, constant: -16),
                mainScrollView.bottomAnchor.constraint(equalTo: saveChangesView.topAnchor, constant: -16),
            
                saveChangesView.bottomAnchor.constraint(equalTo: mainContainerView.bottomAnchor, constant: -16),
                saveChangesView.leadingAnchor.constraint(equalTo: mainContainerView.leadingAnchor, constant: 16),
                saveChangesView.trailingAnchor.constraint(equalTo: mainContainerView.trailingAnchor, constant: -16),
                
                inputsStackView.topAnchor.constraint(equalTo: mainScrollView.topAnchor),
                inputsStackView.bottomAnchor.constraint(equalTo: mainScrollView.bottomAnchor),
                inputsStackView.leadingAnchor.constraint(equalTo: mainScrollView.leadingAnchor),
                inputsStackView.trailingAnchor.constraint(equalTo: mainScrollView.trailingAnchor),
                inputsStackView.widthAnchor.constraint(equalTo: mainScrollView.widthAnchor),
        ])
    }
}
