//
//  ProfilePhotoInteractor.swift
//  ZeusAppExternos
//
//  Created Martin Flores on 30/09/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit
import ZeusServiceCoordinator
import ZeusSessionInfo
import ZeusUtils
import Alamofire

class ProfilePhotoInteractor: ProfilePhotoInteractorInputProtocol {
    weak var presenter: ProfilePhotoInteractorOutputProtocol?
    
    func uploadPhoto(photo: UIImage) {
        
        guard NetworkReachabilityManager()?.isReachable ?? false else {
            self.presenter?.errorUploadPhoto()
            return
        }
        ZULoader.shared.showLoader(.opacity)
        
        ProfilePhotoManager.shared.uploadPhoto(photo: photo) { success in
            ZULoader.shared.hideLoader()
            if success{
                self.presenter?.uploadSuccess()
                return
            }
            self.presenter?.errorUploadPhoto()
        }
    }
}

