//
//  GuestModuleDetailPresenter.swift
//  ZeusAppExternos
//
//  Created Alejandro Rivera on 22/08/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class GuestModuleDetailPresenter {
    weak private var view: GuestModuleDetailViewProtocol?
    var interactor: GuestModuleDetailInteractorInputProtocol?
    private let router: GuestModuleDetailWireframeProtocol

    init(interface: GuestModuleDetailViewProtocol, interactor: GuestModuleDetailInteractorInputProtocol?, router: GuestModuleDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension GuestModuleDetailPresenter: GuestModuleDetailPresenterProtocol {
    
}

extension GuestModuleDetailPresenter: GuestModuleDetailInteractorOutputProtocol {
    
}
