//
//  GuestModuleDetailRouter.swift
//  ZeusAppExternos
//
//  Created Alejandro Rivera on 22/08/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class GuestModuleDetailRouter: GuestModuleDetailWireframeProtocol {
    weak var viewController: UIViewController?

    static func createModule(withInfo info: GuestModuleInfo) -> UIViewController {
        let view = GuestModuleDetailViewController()
        let interactor = GuestModuleDetailInteractor()
        let router = GuestModuleDetailRouter()
        let presenter = GuestModuleDetailPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        view.info = info
        
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
