//
//  GuestModuleDetailInteractor.swift
//  ZeusAppExternos
//
//  Created Alejandro Rivera on 22/08/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class GuestModuleDetailInteractor: GuestModuleDetailInteractorInputProtocol {
    weak var presenter: GuestModuleDetailInteractorOutputProtocol?
}
