//
//  GuestModuleDetailViewController.swift
//  ZeusAppExternos
//
//  Created Alejandro Rivera on 22/08/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit
import ZeusUtils
import ZeusCoreDesignSystem
class GuestModuleDetailViewController: ZDSUDNViewController, GuestModuleDetailViewProtocol {
	var presenter: GuestModuleDetailPresenterProtocol?
    var info: GuestModuleInfo?
    
    var infoView = GuestModuleDetailView()
    
    override func loadView() {
        titleString = info?.name
        super.loadView()
        setupView()
        setActions()
    }

	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    func setupView() {
        navigationController?.isNavigationBarHidden = false
        view.backgroundColor = .white
        view.addSubview(infoView)
        
        udnColor = UDNSkin.global.color
        infoView.translatesAutoresizingMaskIntoConstraints = false
        infoView.iconImageView.image = info?.icon
        infoView.descriptionLabel.text = info?.description
        
        NSLayoutConstraint.activate([
            infoView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            infoView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            infoView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            infoView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor)
        ])
    }
    
    func setActions() {
        infoView.doneButton.addTarget(self, action: #selector(backAction), for: .touchUpInside)
        infoView.loginButton.addTarget(self, action: #selector(goToLogin), for: .touchUpInside)
    }
    
    @objc func goToLogin() {
        SessionManager.logout()
    }
}
