//
//  ZMTSubModulesRouter.swift
//  ZeusAppExternos
//
//  Created Pedro Ivan Soriano Flores on 13/01/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit
import ZeusCoreInterceptor

class ZMTSubModulesRouter: ZMTSubModulesWireframeProtocol {
    weak var viewController: UIViewController?

    static func createModule(permission: [PermissionMenuModel], titleMenu: String?) -> UIViewController {
        let view = ZMTSubModulesViewController()
        let interactor = ZMTSubModulesInteractor()
        let router = ZMTSubModulesRouter()
        let presenter = ZMTSubModulesPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        view.permissions = permission
        view.titleString = titleMenu
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
