//
//  AddGuestPhotoInteractor.swift
//  ZeusAppExternos
//
//  Created Alejandro Rivera on 21/08/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class AddGuestPhotoInteractor: AddGuestPhotoInteractorInputProtocol {
    weak var presenter: AddGuestPhotoInteractorOutputProtocol?
}
