//
//  AddGuestPhotoPresenter.swift
//  ZeusAppExternos
//
//  Created Alejandro Rivera on 21/08/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class AddGuestPhotoPresenter {
    weak private var view: AddGuestPhotoViewProtocol?
    var interactor: AddGuestPhotoInteractorInputProtocol?
    private let router: AddGuestPhotoWireframeProtocol

    init(interface: AddGuestPhotoViewProtocol, interactor: AddGuestPhotoInteractorInputProtocol?, router: AddGuestPhotoWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension AddGuestPhotoPresenter: AddGuestPhotoPresenterProtocol {
    
}

extension AddGuestPhotoPresenter: AddGuestPhotoInteractorOutputProtocol {
    
}
