//
//  HomeViewControllerRouter.swift
//  ZeusAppExternos
//
//  Created Alexander Betanzos Lopez on 30/03/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import ZeusCoreInterceptor
import ZeusTermsConditions
import ZeusSessionInfo

class HomeViewControllerRouter: HomeViewControllerWireframeProtocol {
    weak var viewController: UIViewController?
    
    static func createModule(delegate: HomeViewControllerDelegate) -> UIViewController {
        let view = HomeViewController()
        let interactor = HomeViewControllerInteractor()
        let router = HomeViewControllerRouter()
        let presenter = HomeViewControllerPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        view.delegate = delegate
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func showLegalRequest(update: LegalOptions) {
        let delegate = AlertTermsDelegate(viewController: viewController)
                                                                                                         
        ZCInterceptor.shared.startFlow(forAction: ZCIExternalZeusKeys.alertPrivacyTerms, navigateDelegate: delegate, withInfo: ["update": update, "zeusId": SessionInfo.shared.user?.zeusId])
    }
    
    func openProfilePhoto(delegate: BadgeIDViewDelegate?, image: UIImage?) {
        let vc = BadgeIDRouter.createModule(delegate, image)
        vc.modalPresentationStyle = .overFullScreen
        vc.modalTransitionStyle = .crossDissolve
        viewController?.present(vc, animated: true)
    }
}


protocol HomeViewControllerDelegate {
    func pushToMainNavigationController(viewController: UIViewController)
}
