//
//  HomeViewControllerProtocols.swift
//  ZeusAppExternos
//
//  Created Alexander Betanzos Lopez on 30/03/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import ZeusTermsConditions
import UIKit

//MARK: View Output - (Presenter a View)
protocol HomeViewControllerWireframeProtocol: AnyObject {
    func showLegalRequest(update: LegalOptions)
    func openProfilePhoto(delegate: BadgeIDViewDelegate?, image: UIImage?)
}
//MARK: Router Input - (Presenter -> Router)
protocol HomeViewControllerPresenterProtocol: AnyObject {
    func getPermissions(zeusId: String)
    func validateUniqueSession()
    func validateSession()
    func confirmUniqueSession()
    func confirmNotDisableUser()
    func setMenu(menuFrameworks: [PermissionMenuModel], menuSlide: [PermissionMenuModel])
    func errorGetPermissionsMenu(_ error: String)
    func showUniqueSessionAlert()
    func setupLegalDocuments()
    func showLegalRequest(update: LegalOptions)
    func openProfileBadgeID(delegate: BadgeIDViewDelegate?, image: UIImage?)
    func removeLoader()
    func getAnnouncements()
    func setAnnouncements(announcements: [CarrouselModel])
    func getMenuForSession()
}

//MARK: Interactor input - (Presenter -> Interactor)
protocol HomeViewControllerInteractorProtocol: AnyObject {
    var presenter: HomeViewControllerPresenterProtocol?  { get set }
    func getPermissionsService(zeusId: String)
    func validateUniqueSession()
    func validateSession()
    func confirmUniqueSession()
    func confirmNotDisableUser()
    func setupLegalDocuments()
    func getAnnouncements()
    func getMenuForSession()
}

//MARK: View Output - (Presenter -> View)
protocol HomeViewControllerViewProtocol: AnyObject {
    var presenter: HomeViewControllerPresenterProtocol?  { get set }
    func setMenu(menuFrameworks: [PermissionMenuModel], menuSlide: [PermissionMenuModel])
    func errorNetworkReintent(_ error: String)
    func showUniqueSessionAlert()
    func setupLegalDocuments()
    func removeLoader()
    func setAnnouncements(announcements: [CarrouselModel])
}
