//
//  MyInformationViewRouter.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 11/21/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class MyInformationViewRouter: MyInformationViewWireframeProtocol {
    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        let view = MyInformationViewViewController()
        let interactor = MyInformationViewInteractor()
        let router = MyInformationViewRouter()
        let presenter = MyInformationViewPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func goToVerification(number: String, delegate: VerificationCodeDelegate){
        let vc = VerificationCodeRouter.createModule(number: number, delegate: delegate)
        self.viewController?.navigationController?.pushViewController(vc, animated: false)
    }
}
