//
//  MyInformationViewProtocols.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 11/21/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import Foundation

//MARK: Presenter -> Router
protocol MyInformationViewWireframeProtocol: AnyObject {
    func goToVerification(number: String, delegate: VerificationCodeDelegate)
}

//MARK: View -> Presenter
protocol MyInformationViewPresenterProtocol: AnyObject {
    var interactor: MyInformationViewInteractorInputProtocol? { get set }
    func placeBirthData(catalogId: String)
    func goToVerification(number: String, delegate: VerificationCodeDelegate)
    func getPrivateData()
    func sendVerification(number: String)
    func updateData(data: PersonalInformationRequest)
}

//MARK: Interactor -> Presenter
protocol MyInformationViewInteractorOutputProtocol: AnyObject {
    func setPlacesBirth(catalog: [Catalogue])
    func failAlert()
    func resultSendVerify(success: Bool)
    func setPrivateData(data: PersonalInformation)
    func responseUpdate()
}

//MARK: Presenter -> Interactor
protocol MyInformationViewInteractorInputProtocol: AnyObject {
    var presenter: MyInformationViewInteractorOutputProtocol?  { get set }
    func placeBirthData(catalogId: String)
    func sendVerification(number: String)
    func getPrivateData()
    func updateData(data: PersonalInformationRequest)
}

//MARK: Presenter -> View
protocol MyInformationViewViewProtocol: AnyObject {
    var presenter: MyInformationViewPresenterProtocol?  { get set }
    func setPlacesBirth(catalog: [Catalogue])
    func resultSendVerify(success: Bool)
    func setPrivateData(data: PersonalInformation)
    func failAlert()
    func hideLoader()
    func showLoader()
    func responseUpdate()
}
