//
//  MyInformationViewPresenter.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 11/21/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class MyInformationViewPresenter {
    weak private var view: MyInformationViewViewProtocol?
    var interactor: MyInformationViewInteractorInputProtocol?
    private let router: MyInformationViewWireframeProtocol

    init(interface: MyInformationViewViewProtocol, interactor: MyInformationViewInteractorInputProtocol?, router: MyInformationViewWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension MyInformationViewPresenter: MyInformationViewPresenterProtocol {
 
    func updateData(data: PersonalInformationRequest) {
        view?.showLoader()
        interactor?.updateData(data: data)
    }
    
    func placeBirthData(catalogId: String) {
        interactor?.placeBirthData(catalogId: catalogId)
    }
    
    func sendVerification(number: String) {
        view?.showLoader()
        interactor?.sendVerification(number: number)
    }
    
    func goToVerification(number: String, delegate: VerificationCodeDelegate) {
        router.goToVerification(number: number, delegate: delegate)
    }
    
    func getPrivateData() {
        view?.showLoader()
        interactor?.getPrivateData()
    }
}

extension MyInformationViewPresenter: MyInformationViewInteractorOutputProtocol {
    func responseUpdate() {
        view?.responseUpdate()
    }
    
    func setPlacesBirth(catalog: [Catalogue]) {
        view?.hideLoader()
        view?.setPlacesBirth(catalog: catalog)
    }
    
    func setPrivateData(data: PersonalInformation) {
        view?.setPrivateData(data: data)
    }
    
    func resultSendVerify(success: Bool) {
        view?.hideLoader()
        view?.resultSendVerify(success: success)
    }
    
    func failAlert() {
        view?.hideLoader()
        view?.failAlert()
    }
}
