//
//  ProfilePhotoPhotoRouter.swift
//  ZeusAppExternos
//
//  Created Martin Flores on 30/09/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class ProfilePhotoRouter: ProfilePhotoWireframeProtocol {
    weak var viewController: UIViewController?

    static func createModule(_ previousImage: UIImage?, delegate: ProfilePhotoViewControllerDelegate?) -> UIViewController {
        let view = ProfilePhotoViewController()
        let interactor = ProfilePhotoInteractor()
        let router = ProfilePhotoRouter()
        let presenter = ProfilePhotoPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        view.previousImage = previousImage
        
        interactor.presenter = presenter
        router.viewController = view
        
        view.delegate = delegate
        view.hidesBottomBarWhenPushed = true
        return view
    }
}
