//
//  ProfilePhotoPresenter.swift
//  ZeusAppExternos
//
//  Created Martin Flores on 30/09/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class ProfilePhotoPresenter {
    weak private var view: ProfilePhotoViewProtocol?
    var interactor: ProfilePhotoInteractorInputProtocol?
    private let router: ProfilePhotoWireframeProtocol

    init(interface: ProfilePhotoViewProtocol, interactor: ProfilePhotoInteractorInputProtocol?, router: ProfilePhotoWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension ProfilePhotoPresenter: ProfilePhotoPresenterProtocol {
    func uploadPhoto(photo: UIImage) {
        interactor?.uploadPhoto(photo: photo)
    }
}

extension ProfilePhotoPresenter: ProfilePhotoInteractorOutputProtocol {
    func errorUploadPhoto() {
        view?.errorUploadPhoto()
    }
    
    func uploadSuccess() {
        view?.uploadSuccess()
    }    
}
