//
//  ZMTSubModulesView+Layout.swift
//  ZeusAppExternos
//
//  Created Pedro Ivan Soriano Flores on 13/01/25.
//  Template generated by UPAX Zeus
//

import UIKit

extension ZMTSubModulesView {
    func addViews() {
        addSubview(stackView)
    }
    
    func setupConstraints() {
        NSLayoutConstraint.activate([
            stackView.topAnchor.constraint(equalTo: safeAreaLayoutGuide.topAnchor, constant: 20),
            stackView.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 16),
            stackView.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -16)
        ])
    }
}
