//
//  ProfilePhotoProtocols.swift
//  ZeusAppExternos
//
//  Created Martin Flores on 30/09/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import Foundation
import UIKit

//MARK: Presenter -> Router
protocol ProfilePhotoWireframeProtocol: AnyObject {
    
}

//MARK: View -> Presenter
protocol ProfilePhotoPresenterProtocol: AnyObject {
    var interactor: ProfilePhotoInteractorInputProtocol? { get set }
    
    func uploadPhoto(photo: UIImage)
}

//MARK: Interactor -> Presenter
protocol ProfilePhotoInteractorOutputProtocol: AnyObject {
    func errorUploadPhoto()
    func uploadSuccess()
}

//MARK: Presenter -> Interactor
protocol ProfilePhotoInteractorInputProtocol: AnyObject {
    var presenter: ProfilePhotoInteractorOutputProtocol?  { get set }
    
    func uploadPhoto(photo: UIImage)
}

//MARK: Presenter -> View
protocol ProfilePhotoViewProtocol: AnyObject {
    var presenter: ProfilePhotoPresenterProtocol?  { get set }
    
    func errorUploadPhoto()
    func uploadSuccess()
}
