//
//  EmploymentDataView+Layout.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 12/31/24.
//  Template generated by UPAX Zeus
//

import UIKit
import ZeusCoreDesignSystem

extension EmploymentDataView {
    func addViews() {
        addSubview(mainContainerView)
        mainContainerView.addSubview(mainScrollView)
        mainScrollView.addSubview(inputsStackView)
        
    }
    
    func setupConstraints() {
        NSLayoutConstraint.activate([
            mainContainerView.topAnchor.constraint(equalTo: safeAreaLayoutGuide.topAnchor),
            mainContainerView.leadingAnchor.constraint(equalTo: leadingAnchor),
            mainContainerView.trailingAnchor.constraint(equalTo: trailingAnchor),
            mainContainerView.bottomAnchor.constraint(equalTo: bottomAnchor),
            
            mainScrollView.centerXAnchor.constraint(equalTo: mainContainerView.centerXAnchor),
            mainScrollView.topAnchor.constraint(equalTo: mainContainerView.topAnchor),
            mainScrollView.leadingAnchor.constraint(equalTo: mainContainerView.leadingAnchor),
            mainScrollView.trailingAnchor.constraint(equalTo: mainContainerView.trailingAnchor),
            mainScrollView.bottomAnchor.constraint(equalTo: mainContainerView.bottomAnchor),
            
            inputsStackView.centerXAnchor.constraint(equalTo: mainScrollView.centerXAnchor),
            inputsStackView.topAnchor.constraint(equalTo: mainScrollView.topAnchor, constant: .smallB),
            inputsStackView.leadingAnchor.constraint(equalTo: mainScrollView.leadingAnchor, constant: .smallB),
            inputsStackView.trailingAnchor.constraint(equalTo: mainScrollView.trailingAnchor, constant: -.smallB),
            inputsStackView.bottomAnchor.constraint(equalTo: mainScrollView.bottomAnchor, constant: -.smallB),
        ])
    }
}
