//
//  ZMTSubModulesPresenter.swift
//  ZeusAppExternos
//
//  Created Pedro Ivan Soriano Flores on 13/01/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class ZMTSubModulesPresenter {
    weak private var view: ZMTSubModulesViewProtocol?
    var interactor: ZMTSubModulesInteractorInputProtocol?
    private let router: ZMTSubModulesWireframeProtocol

    init(interface: ZMTSubModulesViewProtocol, interactor: ZMTSubModulesInteractorInputProtocol?, router: ZMTSubModulesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension ZMTSubModulesPresenter: ZMTSubModulesPresenterProtocol {
    
}

extension ZMTSubModulesPresenter: ZMTSubModulesInteractorOutputProtocol {
    
}
