//
//  MyPrivateDataRouter.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 11/5/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class MyPrivateDataRouter: MyPrivateDataWireframeProtocol {
    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        let view = MyPrivateDataViewController()
        let interactor = MyPrivateDataInteractor()
        let router = MyPrivateDataRouter()
        let presenter = MyPrivateDataPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
