//
//  MyPrivateDataPresenter.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 11/5/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class MyPrivateDataPresenter {
    weak private var view: MyPrivateDataViewProtocol?
    var interactor: MyPrivateDataInteractorInputProtocol?
    private let router: MyPrivateDataWireframeProtocol

    init(interface: MyPrivateDataViewProtocol, interactor: MyPrivateDataInteractorInputProtocol?, router: MyPrivateDataWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension MyPrivateDataPresenter: MyPrivateDataPresenterProtocol {
    func updateAdress(adress: AddressRequest) {
        view?.showLoading()
        interactor?.updateAdress(adress: adress)
    }
    
    func getPrivateData() {
        view?.showLoading()
        interactor?.getPrivateData()
    }
    
    func consultCP(CP: String) {
        view?.showLoading()
        interactor?.consultCP(CP: CP)
    }
    
}

extension MyPrivateDataPresenter: MyPrivateDataInteractorOutputProtocol {
    func CPInvalid() {
        view?.removeLoading()
        view?.CPInvalid()
    }
    
    func setInformationError() {
        view?.removeLoading()
        view?.setInformationError()
    }
    
    func resultUpdateAddress(address: AddressInformationResponse?) {
        view?.removeLoading()
        view?.resultUpdateAddress(address: address)
    }
    
    func setPrivateData(data: PersonalInformation) {
        view?.removeLoading()
        view?.setPrivateData(data: data)
    }
    
    func setInformationCP(CPResponse: CPInformation, CP: String) {
        view?.removeLoading()
        view?.setInformationCP(CPResponse: CPResponse, CP: CP)
    }
    
}
