//
//  MyPrivateDataProtocols.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 11/5/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import Foundation

//MARK: Presenter -> Router
protocol MyPrivateDataWireframeProtocol: AnyObject {
    
}

//MARK: View -> Presenter
protocol MyPrivateDataPresenterProtocol: AnyObject {
    var interactor: MyPrivateDataInteractorInputProtocol? { get set }
    func consultCP(CP: String)
    func getPrivateData()
    func updateAdress(adress: AddressRequest)
}

//MARK: Interactor -> Presenter
protocol MyPrivateDataInteractorOutputProtocol: AnyObject {
    func setInformationCP(CPResponse: CPInformation, CP: String)
    func setInformationError()
    func setPrivateData(data: PersonalInformation)
    func resultUpdateAddress(address: AddressInformationResponse?)
    func CPInvalid()
}

//MARK: Presenter -> Interactor
protocol MyPrivateDataInteractorInputProtocol: AnyObject {
    var presenter: MyPrivateDataInteractorOutputProtocol?  { get set }
    func consultStates()
    func consultCP(CP: String)
    func getPrivateData()
    func updateAdress(adress: AddressRequest)
}

//MARK: Presenter -> View
protocol MyPrivateDataViewProtocol: AnyObject {
    var presenter: MyPrivateDataPresenterProtocol?  { get set }
    func setInformationCP(CPResponse: CPInformation, CP: String)
    func setPrivateData(data: PersonalInformation)
    func resultUpdateAddress(address: AddressInformationResponse?)
    func CPInvalid()
    func setInformationError()
    func showLoading()
    func removeLoading()
}
