//
//  ZMTSubModulesProtocols.swift
//  ZeusAppExternos
//
//  Created Pedro Ivan Soriano Flores on 13/01/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import Foundation

//MARK: Presenter -> Router
protocol ZMTSubModulesWireframeProtocol: AnyObject {
    
}

//MARK: View -> Presenter
protocol ZMTSubModulesPresenterProtocol: AnyObject {
    var interactor: ZMTSubModulesInteractorInputProtocol? { get set }
}

//MARK: Interactor -> Presenter
protocol ZMTSubModulesInteractorOutputProtocol: AnyObject {
    
}

//MARK: Presenter -> Interactor
protocol ZMTSubModulesInteractorInputProtocol: AnyObject {
    var presenter: ZMTSubModulesInteractorOutputProtocol?  { get set }
}

//MARK: Presenter -> View
protocol ZMTSubModulesViewProtocol: AnyObject {
    var presenter: ZMTSubModulesPresenterProtocol?  { get set }
}
