//
//  EmploymentDataProtocols.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 12/31/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import Foundation

//MARK: Presenter -> Router
protocol EmploymentDataWireframeProtocol: AnyObject {
    
}

//MARK: View -> Presenter
protocol EmploymentDataPresenterProtocol: AnyObject {
    var interactor: EmploymentDataInteractorInputProtocol? { get set }
    func getPersonalData()
}

//MARK: Interactor -> Presenter
protocol EmploymentDataInteractorOutputProtocol: AnyObject {
    func setPersonalData(personalData: PersonalInformation)
    func failAlert()
}

//MARK: Presenter -> Interactor
protocol EmploymentDataInteractorInputProtocol: AnyObject {
    var presenter: EmploymentDataInteractorOutputProtocol?  { get set }
    func getPersonalData()
}

//MARK: Presenter -> View
protocol EmploymentDataViewProtocol: AnyObject {
    var presenter: EmploymentDataPresenterProtocol?  { get set }
    func setPersonalData(personalData: PersonalInformation)
    func failAlert()
    func hideLoader()
    func showLoader()

}
