//
//  EmploymentDataInteractor.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 12/31/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit
import ZeusSessionInfo
import ZeusServiceCoordinator
import UPAXNetworking

class EmploymentDataInteractor: EmploymentDataInteractorInputProtocol {
    weak var presenter: EmploymentDataInteractorOutputProtocol?
    private let networking = ZeusV2NetworkManager.shared.networking
    
    
    func getPersonalData(){
            guard let collaboratorId = SessionInfo.shared.user?.zeusId else { return }
            print(collaboratorId)
            let pathParams = MyPrivateDataParams(collaboratorId: collaboratorId)
            let url = API.baseURL.absoluteString + "/v2/colaborador/{collaboratorId}/personal-information"
            self.networking.call(url: url, method: .get ,pathParams: pathParams) { (_ result: Swift.Result<PersonalDataResponse, NetError>) in
                switch result {
                case .success(let result):
                    print(result)
                    guard let information = result.personalInformation else { return }
                    self.presenter?.setPersonalData(personalData: information)
                    break
                case .failure(let error):
                    print(error)
                    self.presenter?.failAlert()
                    break
                }
            }
        
    }
}
