//
//  EmploymentDataPresenter.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 12/31/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class EmploymentDataPresenter {
    weak private var view: EmploymentDataViewProtocol?
    var interactor: EmploymentDataInteractorInputProtocol?
    private let router: EmploymentDataWireframeProtocol

    init(interface: EmploymentDataViewProtocol, interactor: EmploymentDataInteractorInputProtocol?, router: EmploymentDataWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension EmploymentDataPresenter: EmploymentDataPresenterProtocol {
    func getPersonalData() {
        view?.showLoader()
        interactor?.getPersonalData()
    }
}

extension EmploymentDataPresenter: EmploymentDataInteractorOutputProtocol {
    
    func setPersonalData(personalData: PersonalInformation) {
        view?.hideLoader()
        view?.setPersonalData(personalData: personalData)
    }
    
    func failAlert() {
        view?.hideLoader()
        view?.failAlert()
    }
}
