//
//  EmploymentDataRouter.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 12/31/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class EmploymentDataRouter: EmploymentDataWireframeProtocol {
    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        let view = EmploymentDataViewController()
        let interactor = EmploymentDataInteractor()
        let router = EmploymentDataRouter()
        let presenter = EmploymentDataPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
