//
//  VerificationCodePresenter.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 11/21/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class VerificationCodePresenter {
    weak private var view: VerificationCodeViewProtocol?
    var interactor: VerificationCodeInteractorInputProtocol?
    private let router: VerificationCodeWireframeProtocol

    init(interface: VerificationCodeViewProtocol, interactor: VerificationCodeInteractorInputProtocol?, router: VerificationCodeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension VerificationCodePresenter: VerificationCodePresenterProtocol {
    func verificationCode(code: String) {
        view?.showLoading()
        interactor?.verificationCode(code: code)
    }
    
    func sendVerification(number: String) {
        interactor?.sendVerification(number: number)
    }
    
    
}

extension VerificationCodePresenter: VerificationCodeInteractorOutputProtocol {
    func failAlert() {
        view?.removeLoading()
        view?.failAlert()
    }
    
    func resultSendVerify(success: Bool) {
        view?.resultSendVerify(success: success)
    }
    
    func resultVerifyCode(success: Bool) {
        view?.removeLoading()
        view?.resultVerifyCode(success: success)
    }
    
    
}
