//
//  VerificationCodeProtocols.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 11/21/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import Foundation

//MARK: Presenter -> Router
protocol VerificationCodeWireframeProtocol: AnyObject {
    
}

//MARK: View -> Presenter
protocol VerificationCodePresenterProtocol: AnyObject {
    var interactor: VerificationCodeInteractorInputProtocol? { get set }
    func sendVerification(number: String)
    func verificationCode(code: String)
}

//MARK: Interactor -> Presenter
protocol VerificationCodeInteractorOutputProtocol: AnyObject {
    func resultSendVerify(success: Bool)
    func resultVerifyCode(success: Bool)
    func failAlert()
}

//MARK: Presenter -> Interactor
protocol VerificationCodeInteractorInputProtocol: AnyObject {
    var presenter: VerificationCodeInteractorOutputProtocol?  { get set }
    func sendVerification(number: String)
    func verificationCode(code: String)
}

//MARK: Presenter -> View
protocol VerificationCodeViewProtocol: AnyObject {
    var presenter: VerificationCodePresenterProtocol?  { get set }
    func resultSendVerify(success: Bool)
    func resultVerifyCode(success: Bool)
    func failAlert()
    func showLoading()
    func removeLoading()
}
