//
//  VerificationCodeRouter.swift
//  ZeusAppExternos
//
//  Created Satori Tech 209 on 11/21/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class VerificationCodeRouter: VerificationCodeWireframeProtocol {
    weak var viewController: UIViewController?

    static func createModule(number: String, delegate: VerificationCodeDelegate) -> UIViewController {
        let view = VerificationCodeViewController()
        let interactor = VerificationCodeInteractor()
        let router = VerificationCodeRouter()
        let presenter = VerificationCodePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        view.number = number
        view.delegate = delegate
        return view
    }
}
